### ISSUE TITLE
COMBINE_PKCS12 doesn't work on alpine

### ISSUE THREAD

**Issue by eksime** [kereis/traefik-certs-dumper#105]
Using the following docker compose configuration, no `cert.p12` was created in the domain's folder when using :alpine, however :latest appears to work

```yml
  certdump:
    image: humenius/traefik-certs-dumper:alpine
    environment:
      ACME_FILE_PATH: /traefik/acme.json
      COMBINE_PKCS12: "yes"
    volumes:
      - ./traefik/acme:/traefik:ro
      - ./letsencrypt:/output:rw
```
