### ISSUE TITLE
still dumping old certificates

### ISSUE THREAD

**Issue by sakearzoo** [kereis/traefik-certs-dumper#130]
```
version: '3.5'

services:
  certdumper:
    image: humenius/traefik-certs-dumper:edge-arm64v8
    volumes:
    - /home/traefik/acme.json:/traefik/acme.json:ro
    - /home/adguard/data/certs:/output:rw
    - /home/anonaddy/data/certs:/output1:rw
    - /var/run/docker.sock:/var/run/docker.sock:ro
    - /home/anonaddy/data/hook.sh:/hook/hook.sh:ro
    environment:
    - CERTIFICATE_FILE_NAME=fullchain
    - PRIVATE_KEY_FILE_NAME=privkey
    - OVERRIDE_UID=1000
    - OVERRIDE_GID=1000
    
    network_mode: "none" 
```

after traefik renews the certificate from letsencrypt . the docker container still dumping old certs. i have seen that acme.json still contains old certs and also the new certs for my domain. but the docker dumping old certs not the latest certs . is there any way to fix this?
