### ISSUE TITLE
Hook issue

### ISSUE THREAD

**Issue by foorschtbar** [kereis/traefik-certs-dumper#137]
Is there any known issue with the Post-hook script? I set it up like in the example, but it doesn't run. If i attach to the container and run it from the cli, it works fine.

```yml
volumes:
[...]
- ./data/output:/output:rw
- ./hook.sh:/hook/hook.sh:ro
environment:
- OVERRIDE_UID=1001
- OVERRIDE_GID=1001
- POST_HOOK_FILE_PATH=/hook/hook.sh
```

hook.sh (-rwxrwxr-x)
```bash
#!/bin/bash

touch /output/posthook.example

chmod 0644 /output/*.pem
```
