### ISSUE TITLE
Where to put certdumper? Traefik or Mailcow? Will certs be dumped automatically again if the root domain gets renewed certificates?

### ISSUE THREAD

**Issue by aronmgv** [kereis/traefik-certs-dumper#185]
Hey,

For my Mailcow behind Traefik setup I just moved from different certdumper to this one and am curious where I should put this service. Into Traefik compose file or Mailcow override compose file? For the old certdumper I used to have it in traefik compose file but for this one I set it up into Mailcow override because of environment variables to restart mailcow services after the dump..
My main concern is that once certs get renewed for my domain will they be automatically dumped into Mailcow (without manual invervention)?

Thanks!

```yml
version: '2.1'

services:
    certdumper:
        image: humenius/traefik-certs-dumper
        command: --restart-containers ${COMPOSE_PROJECT_NAME}-postfix-mailcow-1,${COMPOSE_PROJECT_NAME}-nginx-mailcow-1,${COMPOSE_PROJECT_NAME}-dovecot-mailcow-1
        network_mode: none
        volumes:
          # Mount the volume which contains Traefik's `acme.json' file
          #   Configure the external name in the volume definition
          - /docker/+traefik/acme:/traefik:ro
          # Mount mailcow's SSL folder
          - ./data/assets/ssl/:/output:rw
          # Mount docker socket to restart containers
          - /var/run/docker.sock:/var/run/docker.sock:ro
        restart: always
        environment:
          # only change this, if you're using another domain for mailcow's web frontend compared to the standard config
          - DOMAIN=example.com
```
