### ISSUE TITLE
Pasring Error for Trafik V3

### ISSUE THREAD

**Issue by t-abraham** [kereis/traefik-certs-dumper#193]
Hi i am having an issue for the container. It cannot parse. Can anyone help me out

**YAML**
```
services:
  certdumper:
    command: --restart-containers plex
    container_name: Traefik_cert_dumper
    depends_on:
    - traefik
    environment:
      ACME_FILE_PATH: /traefik/lets_encrypt_ssl.json
      COMBINED_PEM: concatted_cert.pem
      COMBINE_PKCS12: "yes"
    image: ghcr.io/kereis/traefik-certs-dumper:latest
    labels:
      com.centurylinklabs.watchtower.enable: "true"
    logging:
      options:
        max-file: '3'
        max-size: 5m
    networks:
      CognitiveSystems: {}
    user: 0:0
    volumes:
    - /home/data/shared/certificates/ssl:/output:rw
    - /home/traefik/lets_encrypt_ssl.json:/traefik/lets_encrypt_ssl.json:ro
    - /var/run/docker.sock:/var/run/docker.sock:ro
  traefik:
    command: redacted
    environment: redacted
    container_name: Traefik
    healthcheck:
      test:
      - NONE
    image: traefik:latest
    labels: redacted
    logging:
      options:
        max-file: '3'
        max-size: 5m
    ports:redacted
    restart: unless-stopped
    user: redacted
    volumes:
    - /etc/localtime:/etc/localtime:ro
    - /home/traefik/lets_encrypt_ssl.json:/lets_encrypt_ssl.json:rw
    - /home/traefik/users.htpasswd:/users.htpasswd:rw
    - /var/run/docker.sock:/var/run/docker.sock:ro
version: '3.5'
```

**Error**
```
Error: v2: dump failed: failed to unmarshal file "/traefik/lets_encrypt_ssl.json": invalid character 'a' looking for beginning of value

Usage:

  traefik-certs-dumper file [flags]

Flags:

  -h, --help             help for file

      --source string    Path to 'acme.json' file. (default "./acme.json")

      --version string   Traefik version. If empty use v1. Possible values: 'v2'.

Global Flags:

      --clean              Clean destination folder before dumping content. (default true)

      --config string      config file (default is $HOME/.traefik-certs-dumper.yaml)

      --crt-ext string     The file extension of the generated certificates. (default ".crt")

      --crt-name string    The file name (without extension) of the generated certificates. (default "certificate")

      --dest string        Path to store the dump content. (default "./dump")

      --domain-subdir      Use domain as sub-directory.

      --key-ext string     The file extension of the generated private keys. (default ".key")

      --key-name string    The file name (without extension) of the generated private keys. (default "privatekey")

      --post-hook string   Execute a command only if changes occurs on the data source. (works only with the watch mode)

      --watch              Enable watching changes.

2024/06/24 22:47:39 root.go:45: v2: dump failed: failed to unmarshal file "/traefik/lets_encrypt_ssl.json": invalid character 'a' looking for beginning of value

[2024-06-24T22:47:39+0000]: Certificates for domain '*' don't exist. Omitting...
```
