### ISSUE TITLE
Multiple DockerHost to restart containers in different vms

### ISSUE THREAD

**Issue by t-abraham** [kereis/traefik-certs-dumper#195]
[Containers restart #1](https://github.com/kereis/traefik-certs-dumper/issues/1) you added the option to restart containers using the RESTART_CONTAINERS env var and the use of DOCKER_HOST to add the proxy. But is it possible to add support for multiple docker hosts? Like this

```
version: "3.7"

services:
  test:
    image: ghcr.io/kereis/traefik-certs-dumper:latest
    restart: always
    environment:
      - DOCKER_HOST=10.20.30.101:2375,10.20.30.102:2375,10.20.30.103:2375
      - RESTART_CONTAINERS=container1,container2,container3
```

here container1 is at 10.20.30.102:237, container2 is at 10.20.30.103:237, container3 is at 10.20.30.101:237

something like this...
