### ISSUE TITLE
no such file or directory

### ISSUE THREAD

**Issue by eshkq** [kereis/traefik-certs-dumper#196]
Hi, I ran into a problem, I can't assign a path to the acme.json file, no matter what path I set, it still substitutes "/traefik/acme.json" my file is located at
/root/docker/traefik/acme.json:/acme.json
I will provide the docker-compose file and log below

```
version: '2.1'
services:
  nginx-mailcow:
    expose:
      - "10080"
    networks:
      - proxy
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.nginx-mailcow.entrypoints=http"
      - "traefik.http.routers.nginx-mailcow.rule=HostRegexp(`{host:(autodiscover|autoconfig|webmail|mail|email).+}`)"
      - "traefik.http.middlewares.nginx-mailcow-https-redirect.redirectscheme.scheme=https"
      - "traefik.http.routers.nginx-mailcow.middlewares=nginx-mailcow-https-redirect"
      - "traefik.http.routers.nginx-mailcow-secure.entrypoints=https"
      - "traefik.http.routers.nginx-mailcow-secure.rule=Host(`mail.examle.com`)" 
      - "traefik.http.routers.nginx-mailcow-secure.tls=true"
      - "traefik.http.routers.nginx-mailcow-secure.tls.certresolver=http"
      - "traefik.http.routers.nginx-mailcow-secure.service=nginx-mailcow"
      - "traefik.http.services.nginx-mailcow.loadbalancer.server.port=10080"
      - "traefik.docker.network=proxy"  
  certdumper:
        image: ghcr.io/kereis/traefik-certs-dumper
        command: --restart-containers ${COMPOSE_PROJECT_NAME}-postfix-mailcow-1,${COMPOSE_PROJECT_NAME}-nginx-mailcow-1,${COMPOSE_PROJECT_NAME}-dovecot-mailcow-1
        network_mode: none
        volumes:
          # Mount the volume which contains Traefik's `acme.json' file
          #   Configure the external name in the volume definition
          - /root/docker/traefik/acme.json:/acme.json
          # Mount mailcow's SSL folder
          - ./data/assets/ssl/:/output:rw
          # Mount docker socket to restart containers
          - /var/run/docker.sock:/var/run/docker.sock:ro
        restart: always
        environment:
          # only change this, if you're using another domain for mailcow's web frontend compared to the standard config
          - DOMAIN=mail.examle.com
networks:
  proxy:
    external: true
```

```
2025/01/17 17:56:17 root.go:45: v2: dump failed: failed to open file "/traefik/acme.json": open /traefik/acme.json: no such file or directory

[2025-01-17T17:56:17+0000]: Certificates for domain 'mail.examle.com' don't exist. Omitting...

[2025-01-17T17:56:17+0000]: /traefik/acme.json is not a file. Retrying...
```

**Comment by kereis** [comment]
Hi,

if you need to mount the file at root dir of the file system, you need to set `ACME_FILE_PATH` as well. In this case: `ACME_FILE_PATH=/acme.json`. Otherwise, mount `acme.json` to `/traefik/acme.json` instead.

Hope it helps.

**Comment by kereis** [comment]
Did you make sure that `./traefik/acme` is a file and not a directory?

**Comment by kereis** [comment]
I think you mixed up the mount syntax. The left hand side of the colon (`:`) represents the path on the host system, right hand side container path.

**Comment by kereis** [comment]
If the path to your `acme.json` on your host system is `/root/docker/traefik/acme.json`, then your compose file needs to look like this:
```yaml
certdumper:
        image: ghcr.io/kereis/traefik-certs-dumper
        command: --restart-containers ${COMPOSE_PROJECT_NAME}-postfix-mailcow-1,${COMPOSE_PROJECT_NAME}-nginx-mailcow-1,${COMPOSE_PROJECT_NAME}-dovecot-mailcow-1
        network_mode: none
        volumes:
          # Mount the volume which contains Traefik's `acme.json' file
          #   Configure the external name in the volume definition
          - /root/docker/traefik/acme.json:/traefik/acme.json:ro
          # Mount mailcow's SSL folder
          - ./data/assets/ssl/:/output:rw
          # Mount docker socket to restart containers
          - /var/run/docker.sock:/var/run/docker.sock:ro
        restart: always
        environment:
          # only change this, if you're using another domain for mailcow's web frontend compared to the standard config
          - DOMAIN=mail.example.com
```

I hope this works. 😄
